### PR TITLE
Updatefix

### PR DESCRIPTION
**Pull request by gcavallo**
Update packages, fix errors, and optimize database size.
- Fix and clean the scripts with no change to the code itself
- Update packages and database
- Automate and optimize the json files, see commit 0d63c35

Tested and working, the smaller file size may help publish it to the Chrome store.

### CODE REVIEW

**Comment by gcavallo** [comment]
I'm done with this particular branch. I had to do an "history rewrite" by deleting database files, as GitHub was blocking my push according to their "large file" policy. No code has actually been modified from your history so it should be easy to deal with conflicts.

Feel free to contact me.

**Comment by jacobgelling** [comment]
That's quite a lot of changes, thanks! :smile: 

Grunt build is failing for me on your branch when writing the IPv6 db...will merge as soon as I sort it out, then do a longer overdue push to the Chrome web store.

**Comment by jacobgelling** [comment]
Merged successfully and publishing to Chrome web store as I type this.

Thanks for the well needed tidy up of the code and the abundance of fixes.

As you've probably discovered, GeoFlag isn't particularly fast at location lookups - I think I'm going to have another go at writing a more optimized (and customisable) version of GeoFlag soon. Hopefully we can collaborate on it :+1:

**Comment by gcavallo** [comment]
Thanks for the merge!

I noticed last night I'm not caching the country code, so the flag can be wrong. It's fixed in my HEAD, I'll test it a little and push another branch next week.

**Pull request merged**
